name: check

on:
  push:
    branches:
      - main

jobs:
  calculate-size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.29.0
      - uses: sarthak-saxena/JSBundleSize@master
        with:
          bootstrap: "pnpm i"
          build_command: "pnpm run build"
          dist_path: "dist"
          token: ${{ secrets.GITHUB_TOKEN }}
